"""Scrublet-style differentiable doublet detection for single-cell data.

This module provides a differentiable implementation of doublet detection
inspired by Scrublet. Synthetic doublets are generated by summing random
pairs of observed cell profiles, then real cells are scored by measuring
their similarity to synthetic doublets in PCA space via k-NN.

Key technique: Soft k-NN neighbor counting with differentiable thresholding
enables gradient flow back through the doublet scoring pipeline.

Applications: Identifying doublet artifacts in scRNA-seq data as a
preprocessing step before downstream analysis (clustering, trajectory, DE).
"""

from dataclasses import dataclass
from typing import Any

import jax
import jax.numpy as jnp
from datarax.core.config import OperatorConfig
from datarax.core.operator import OperatorModule
from flax import nnx
from jaxtyping import Array, Float, PyTree

from diffbio.core.graph_utils import compute_pairwise_distances


@dataclass
class DoubletScorerConfig(OperatorConfig):
    """Configuration for Scrublet-style doublet detection.

    Attributes:
        n_neighbors: Base number of nearest neighbors for scoring (adjusted
            upward to account for synthetic pool size).
        expected_doublet_rate: Prior expected fraction of doublets (rho in
            the Bayesian likelihood ratio).
        sim_doublet_ratio: Ratio of synthetic doublets to real cells. Scrublet
            default is 2.0, meaning 2x as many synthetics as real cells.
        n_pca_components: Number of PCA components for embedding.
        n_genes: Number of genes in expression profiles.
        threshold_temperature: Temperature for sigmoid doublet thresholding.
        stochastic: Whether the operator uses randomness (always True).
        stream_name: RNG stream name for doublet pair selection.
    """

    n_neighbors: int = 30
    expected_doublet_rate: float = 0.06
    sim_doublet_ratio: float = 2.0
    n_pca_components: int = 30
    n_genes: int = 2000
    threshold_temperature: float = 10.0
    stochastic: bool = True
    stream_name: str | None = "sample"


class DifferentiableDoubletScorer(OperatorModule):
    """Differentiable Scrublet-style doublet detection operator.

    Detects doublets by generating synthetic doublet profiles from random
    cell pairs, embedding real and synthetic cells into PCA space, and
    scoring each real cell via the Bayesian k-NN likelihood ratio from
    Scrublet (Wolock et al., 2019).

    Algorithm:
        1. Generate ``n_cells * sim_doublet_ratio`` synthetic doublets
        2. Concatenate real and synthetic cells
        3. PCA-embed via truncated SVD
        4. Compute pairwise distances in PCA space
        5. Adjust k upward: ``k_adj = round(k * (1 + n_syn / n_cells))``
        6. Count soft synthetic neighbors in each real cell's k-NN
        7. Compute Laplace-smoothed fraction ``q`` of synthetic neighbors
        8. Bayesian likelihood ratio: ``Ld = q * rho / r / denom``
        9. Apply sigmoid threshold for predicted doublet calls

    Args:
        config: DoubletScorerConfig with operator parameters.
        rngs: Flax NNX random number generators.
        name: Optional operator name.

    Example:
        >>> config = DoubletScorerConfig(n_neighbors=30, n_pca_components=30,
        ...                              n_genes=2000)
        >>> scorer = DifferentiableDoubletScorer(config, rngs=nnx.Rngs(0))
        >>> rng = jax.random.key(0)
        >>> rp = scorer.generate_random_params(rng, {"counts": (500, 2000)})
        >>> result, state, meta = scorer.apply({"counts": counts}, {}, None,
        ...                                    random_params=rp)
        >>> result["doublet_scores"].shape
        (500,)
    """

    def __init__(
        self,
        config: DoubletScorerConfig,
        *,
        rngs: nnx.Rngs | None = None,
        name: str | None = None,
    ) -> None:
        """Initialize the doublet scorer.

        Args:
            config: Doublet scorer configuration.
            rngs: Random number generators for stochastic operations.
            name: Optional operator name.
        """
        super().__init__(config, rngs=rngs, name=name)

    def generate_random_params(
        self,
        rng: jax.Array,
        data_shapes: PyTree,
    ) -> jax.Array:
        """Generate random parameters for doublet pair selection.

        Produces two arrays of random cell indices used to form synthetic
        doublets by pairwise summation.

        Args:
            rng: JAX random key.
            data_shapes: PyTree with shapes, must contain ``"counts"`` key
                whose first dimension is the number of cells.

        Returns:
            A JAX random key for reproducible pair generation inside apply.
        """
        return rng

    def _generate_synthetic_doublets(
        self,
        counts: Float[Array, "n_cells n_genes"],
        rng: jax.Array,
        sim_doublet_ratio: float,
    ) -> Float[Array, "n_synthetic n_genes"]:
        """Generate synthetic doublets by summing random cell pairs.

        The number of synthetic doublets is ``n_cells * sim_doublet_ratio``,
        matching Scrublet's default 2:1 synthetic-to-real ratio.

        Args:
            counts: Real count matrix of shape ``(n_cells, n_genes)``.
            rng: JAX random key for pair selection.
            sim_doublet_ratio: Ratio of synthetic doublets to real cells.

        Returns:
            Synthetic doublet profiles of shape
            ``(n_cells * sim_doublet_ratio, n_genes)``.
        """
        n_cells = counts.shape[0]
        n_synthetic = int(n_cells * sim_doublet_ratio)
        k1, k2 = jax.random.split(rng)
        idx_a = jax.random.randint(k1, (n_synthetic,), 0, n_cells)
        idx_b = jax.random.randint(k2, (n_synthetic,), 0, n_cells)
        return counts[idx_a] + counts[idx_b]

    def _pca_embed(
        self,
        data: Float[Array, "n_total n_genes"],
        n_components: int,
    ) -> Float[Array, "n_total n_components"]:
        """Embed data into PCA space via truncated SVD.

        Centers the data, computes SVD, and projects onto the top
        ``n_components`` principal components.

        Args:
            data: Input matrix of shape ``(n_total, n_genes)``.
            n_components: Number of PCA dimensions to keep.

        Returns:
            PCA embeddings of shape ``(n_total, n_components)``.
        """
        centered = data - jnp.mean(data, axis=0, keepdims=True)
        # Truncated SVD: project onto top-n_components right singular vectors
        _, _, vt = jnp.linalg.svd(centered, full_matrices=False)
        # Clamp n_components to available dimensions
        n_components_eff = min(n_components, vt.shape[0])
        projection = vt[:n_components_eff]  # (n_components_eff, n_genes)
        return centered @ projection.T

    def _compute_soft_knn_synthetic_count(
        self,
        distances: Float[Array, "n_real n_total"],
        n_real: int,
        n_total: int,
        k_adj: int,
    ) -> Float[Array, "n_real"]:
        """Compute soft count of synthetic neighbors in adjusted k-NN.

        Uses a softmax-weighted membership approach: for each real cell,
        the ``k_adj`` smallest distances are selected, and the weighted
        count of synthetic neighbors is returned for the Bayesian
        likelihood-ratio formula.

        Args:
            distances: Distance matrix from real cells to all cells,
                shape ``(n_real, n_total)``.
            n_real: Number of real cells.
            n_total: Total number of cells (real + synthetic).
            k_adj: Adjusted number of nearest neighbors (accounts for
                synthetic pool size).

        Returns:
            Soft synthetic neighbor count per real cell, shape ``(n_real,)``.
        """
        k_eff = min(k_adj, n_total - 1)

        # Create label vector: 0 for real, 1 for synthetic
        is_synthetic = jnp.concatenate(
            [
                jnp.zeros(n_real),
                jnp.ones(n_total - n_real),
            ]
        )

        # Mask self-distances for real cells (first n_real columns correspond to real)
        self_mask = jnp.eye(n_real, n_total) * 1e10
        masked_distances = distances + self_mask

        # Soft k-NN: convert distances to weights via negative exponential
        # Use temperature scaling for smoother gradients
        sigma = jnp.sort(masked_distances, axis=-1)[:, k_eff - 1 : k_eff]
        sigma = jnp.maximum(sigma, 1e-8)
        weights = jnp.exp(-masked_distances / sigma)

        # Zero out self-connections
        weights = weights * (1.0 - jnp.eye(n_real, n_total))

        # Get top-k mask via soft approximation: use sorted threshold
        sorted_dists = jnp.sort(masked_distances, axis=-1)
        kth_dist = sorted_dists[:, k_eff - 1 : k_eff]  # (n_real, 1)
        # Soft indicator for being within k-NN (sigmoid approximation)
        temperature = 10.0
        knn_mask = jax.nn.sigmoid(temperature * (kth_dist - masked_distances))

        # Weighted synthetic count (not fraction -- the Bayesian formula needs count)
        masked_weights = weights * knn_mask
        synthetic_weight = masked_weights @ is_synthetic

        return synthetic_weight

    def apply(
        self,
        data: PyTree,
        state: PyTree,
        metadata: dict[str, Any] | None,
        random_params: Any = None,
        stats: dict[str, Any] | None = None,
    ) -> tuple[PyTree, PyTree, dict[str, Any] | None]:
        """Apply doublet detection to single-cell count data.

        Implements Scrublet's Bayesian k-NN likelihood-ratio scoring:

        1. Generate ``n_cells * sim_doublet_ratio`` synthetic doublets
        2. Adjust k upward: ``k_adj = round(k * (1 + n_syn / n_cells))``
        3. For each real cell, count synthetic neighbors in its k-NN
        4. Compute Laplace-smoothed fraction ``q = (syn_count + 1) / (k_adj + 2)``
        5. Bayesian likelihood ratio:
           ``Ld = q * rho / r / (1 - rho - q*(1 - rho - rho/r))``

        Args:
            data: Dictionary containing:
                - ``"counts"``: Gene expression matrix ``(n_cells, n_genes)``
            state: Element state (passed through unchanged).
            metadata: Element metadata (passed through unchanged).
            random_params: JAX random key for synthetic doublet generation.
            stats: Not used.

        Returns:
            Tuple of (transformed_data, state, metadata):
                - transformed_data contains:

                    - ``"counts"``: Original counts
                    - ``"doublet_scores"``: Bayesian likelihood ratio per cell
                    - ``"predicted_doublets"``: Soft doublet predictions in [0, 1]
                - state is passed through unchanged
                - metadata is passed through unchanged
        """
        counts = data["counts"]
        n_cells = counts.shape[0]
        config = self.config

        # Use provided random key or fallback
        rng = random_params if random_params is not None else jax.random.key(0)

        # Step 1: Generate synthetic doublets (n_cells * sim_doublet_ratio)
        synthetic = self._generate_synthetic_doublets(counts, rng, config.sim_doublet_ratio)
        n_synthetic = synthetic.shape[0]

        # Step 2: Combine real + synthetic
        combined = jnp.concatenate([counts, synthetic], axis=0)
        n_total = combined.shape[0]

        # Step 3: PCA embed
        pca = self._pca_embed(combined, config.n_pca_components)

        # Step 4: Pairwise distances in PCA space, then extract real-to-all block
        distances = compute_pairwise_distances(pca)
        real_to_all = distances[:n_cells]

        # Step 5: Adjust k for the enlarged pool (Scrublet convention)
        k_adj = round(config.n_neighbors * (1 + n_synthetic / n_cells))

        # Step 6: Soft k-NN synthetic neighbor count
        syn_neighbor_count = self._compute_soft_knn_synthetic_count(
            real_to_all, n_cells, n_total, k_adj
        )

        # Step 7: Bayesian likelihood-ratio scoring (Scrublet formula)
        # q = Laplace-smoothed fraction of synthetic neighbors
        q = (syn_neighbor_count + 1) / (k_adj + 2)
        rho = config.expected_doublet_rate
        r = n_synthetic / n_cells  # synthetic-to-real ratio

        # Denominator with numerical guard to avoid division by zero
        denominator = jnp.maximum(1 - rho - q * (1 - rho - rho / r), 1e-8)
        doublet_scores = q * rho / r / denominator

        # Step 8: Soft threshold for predicted doublets (sigmoid on score)
        predicted_doublets = jax.nn.sigmoid(config.threshold_temperature * (doublet_scores - 0.5))

        transformed_data = {
            **data,
            "doublet_scores": doublet_scores,
            "predicted_doublets": predicted_doublets,
        }

        return transformed_data, state, metadata
