"""Scrublet-style differentiable doublet detection for single-cell data.

This module provides a differentiable implementation of doublet detection
inspired by Scrublet. Synthetic doublets are generated by summing random
pairs of observed cell profiles, then real cells are scored by measuring
their similarity to synthetic doublets in PCA space via k-NN.

Key technique: Soft k-NN neighbor counting with differentiable thresholding
enables gradient flow back through the doublet scoring pipeline.

Applications: Identifying doublet artifacts in scRNA-seq data as a
preprocessing step before downstream analysis (clustering, trajectory, DE).
"""

from dataclasses import dataclass
from typing import Any

import jax
import jax.numpy as jnp
from datarax.core.config import OperatorConfig
from datarax.core.operator import OperatorModule
from flax import nnx
from jaxtyping import Array, Float, PyTree

from diffbio.core.graph_utils import compute_pairwise_distances


@dataclass
class DoubletScorerConfig(OperatorConfig):
    """Configuration for Scrublet-style doublet detection.

    Attributes:
        n_neighbors: Number of nearest neighbors for scoring.
        expected_doublet_rate: Expected fraction of doublets in the dataset.
        n_pca_components: Number of PCA components for embedding.
        n_genes: Number of genes in expression profiles.
        threshold_temperature: Temperature for sigmoid doublet thresholding.
        stochastic: Whether the operator uses randomness (always True).
        stream_name: RNG stream name for doublet pair selection.
    """

    n_neighbors: int = 30
    expected_doublet_rate: float = 0.06
    n_pca_components: int = 30
    n_genes: int = 2000
    threshold_temperature: float = 10.0
    stochastic: bool = True
    stream_name: str | None = "sample"


class DifferentiableDoubletScorer(OperatorModule):
    """Differentiable Scrublet-style doublet detection operator.

    Detects doublets by generating synthetic doublet profiles from random
    cell pairs, embedding real and synthetic cells into PCA space, and
    scoring each real cell by the fraction of its k-nearest neighbors
    that are synthetic.

    Algorithm:
        1. Generate synthetic doublets by summing random cell pairs
        2. Concatenate real and synthetic cells
        3. PCA-embed via truncated SVD
        4. Compute pairwise distances in PCA space
        5. For each real cell, compute soft fraction of k-NN that are synthetic
        6. Normalize score by expected synthetic fraction
        7. Apply sigmoid threshold for predicted doublet calls

    Args:
        config: DoubletScorerConfig with operator parameters.
        rngs: Flax NNX random number generators.
        name: Optional operator name.

    Example:
        >>> config = DoubletScorerConfig(n_neighbors=30, n_pca_components=30,
        ...                              n_genes=2000)
        >>> scorer = DifferentiableDoubletScorer(config, rngs=nnx.Rngs(0))
        >>> rng = jax.random.key(0)
        >>> rp = scorer.generate_random_params(rng, {"counts": (500, 2000)})
        >>> result, state, meta = scorer.apply({"counts": counts}, {}, None,
        ...                                    random_params=rp)
        >>> result["doublet_scores"].shape
        (500,)
    """

    def __init__(
        self,
        config: DoubletScorerConfig,
        *,
        rngs: nnx.Rngs | None = None,
        name: str | None = None,
    ) -> None:
        """Initialize the doublet scorer.

        Args:
            config: Doublet scorer configuration.
            rngs: Random number generators for stochastic operations.
            name: Optional operator name.
        """
        super().__init__(config, rngs=rngs, name=name)

    def generate_random_params(
        self,
        rng: jax.Array,
        data_shapes: PyTree,
    ) -> jax.Array:
        """Generate random parameters for doublet pair selection.

        Produces two arrays of random cell indices used to form synthetic
        doublets by pairwise summation.

        Args:
            rng: JAX random key.
            data_shapes: PyTree with shapes, must contain ``"counts"`` key
                whose first dimension is the number of cells.

        Returns:
            A JAX random key for reproducible pair generation inside apply.
        """
        return rng

    def _generate_synthetic_doublets(
        self,
        counts: Float[Array, "n_cells n_genes"],
        rng: jax.Array,
    ) -> Float[Array, "n_synthetic n_genes"]:
        """Generate synthetic doublets by summing random cell pairs.

        Args:
            counts: Real count matrix of shape ``(n_cells, n_genes)``.
            rng: JAX random key for pair selection.

        Returns:
            Synthetic doublet profiles of shape ``(n_cells, n_genes)``.
        """
        n_cells = counts.shape[0]
        k1, k2 = jax.random.split(rng)
        idx_a = jax.random.randint(k1, (n_cells,), 0, n_cells)
        idx_b = jax.random.randint(k2, (n_cells,), 0, n_cells)
        return counts[idx_a] + counts[idx_b]

    def _pca_embed(
        self,
        data: Float[Array, "n_total n_genes"],
        n_components: int,
    ) -> Float[Array, "n_total n_components"]:
        """Embed data into PCA space via truncated SVD.

        Centers the data, computes SVD, and projects onto the top
        ``n_components`` principal components.

        Args:
            data: Input matrix of shape ``(n_total, n_genes)``.
            n_components: Number of PCA dimensions to keep.

        Returns:
            PCA embeddings of shape ``(n_total, n_components)``.
        """
        centered = data - jnp.mean(data, axis=0, keepdims=True)
        # Truncated SVD: project onto top-n_components right singular vectors
        _, _, vt = jnp.linalg.svd(centered, full_matrices=False)
        # Clamp n_components to available dimensions
        n_components_eff = min(n_components, vt.shape[0])
        projection = vt[:n_components_eff]  # (n_components_eff, n_genes)
        return centered @ projection.T

    def _compute_soft_knn_fraction(
        self,
        distances: Float[Array, "n_real n_total"],
        n_real: int,
        n_total: int,
        k: int,
    ) -> Float[Array, "n_real"]:
        """Compute soft fraction of k-nearest neighbors that are synthetic.

        Uses a softmax-weighted membership approach: for each real cell,
        the k smallest distances are selected, and the fraction of those
        neighbors that are synthetic is computed as a differentiable score.

        Args:
            distances: Distance matrix from real cells to all cells,
                shape ``(n_real, n_total)``.
            n_real: Number of real cells.
            n_total: Total number of cells (real + synthetic).
            k: Number of nearest neighbors.

        Returns:
            Soft synthetic fraction per real cell, shape ``(n_real,)``.
        """
        k_eff = min(k, n_total - 1)

        # Create label vector: 0 for real, 1 for synthetic
        is_synthetic = jnp.concatenate([
            jnp.zeros(n_real),
            jnp.ones(n_total - n_real),
        ])

        # Mask self-distances for real cells (first n_real columns correspond to real)
        self_mask = jnp.eye(n_real, n_total) * 1e10
        masked_distances = distances + self_mask

        # Soft k-NN: convert distances to weights via negative exponential
        # Use temperature scaling for smoother gradients
        sigma = jnp.sort(masked_distances, axis=-1)[:, k_eff - 1:k_eff]
        sigma = jnp.maximum(sigma, 1e-8)
        weights = jnp.exp(-masked_distances / sigma)

        # Zero out self-connections
        weights = weights * (1.0 - jnp.eye(n_real, n_total))

        # Get top-k mask via soft approximation: use sorted threshold
        sorted_dists = jnp.sort(masked_distances, axis=-1)
        kth_dist = sorted_dists[:, k_eff - 1:k_eff]  # (n_real, 1)
        # Soft indicator for being within k-NN (sigmoid approximation)
        temperature = 10.0
        knn_mask = jax.nn.sigmoid(temperature * (kth_dist - masked_distances))

        # Weighted synthetic fraction
        masked_weights = weights * knn_mask
        synthetic_weight = masked_weights @ is_synthetic
        total_weight = jnp.sum(masked_weights, axis=-1) + 1e-8

        return synthetic_weight / total_weight

    def apply(
        self,
        data: PyTree,
        state: PyTree,
        metadata: dict[str, Any] | None,
        random_params: Any = None,
        stats: dict[str, Any] | None = None,
    ) -> tuple[PyTree, PyTree, dict[str, Any] | None]:
        """Apply doublet detection to single-cell count data.

        Args:
            data: Dictionary containing:
                - ``"counts"``: Gene expression matrix ``(n_cells, n_genes)``
            state: Element state (passed through unchanged).
            metadata: Element metadata (passed through unchanged).
            random_params: JAX random key for synthetic doublet generation.
            stats: Not used.

        Returns:
            Tuple of (transformed_data, state, metadata):
                - transformed_data contains:

                    - ``"counts"``: Original counts
                    - ``"doublet_scores"``: Per-cell doublet score in [0, 1]
                    - ``"predicted_doublets"``: Soft doublet predictions in [0, 1]
                - state is passed through unchanged
                - metadata is passed through unchanged
        """
        counts = data["counts"]
        n_cells = counts.shape[0]

        # Use provided random key or fallback
        rng = random_params if random_params is not None else jax.random.key(0)

        # Step 1: Generate synthetic doublets
        synthetic = self._generate_synthetic_doublets(counts, rng)

        # Step 2: Combine real + synthetic
        combined = jnp.concatenate([counts, synthetic], axis=0)
        n_total = combined.shape[0]

        # Step 3: PCA embed
        pca = self._pca_embed(combined, self.config.n_pca_components)

        # Step 4: Pairwise distances in PCA space, then extract real-to-all block
        distances = compute_pairwise_distances(pca)
        real_to_all = distances[:n_cells]

        # Step 5: Soft k-NN fraction of synthetic neighbors
        raw_scores = self._compute_soft_knn_fraction(
            real_to_all, n_cells, n_total, self.config.n_neighbors
        )

        # Step 6: Normalize by expected fraction
        fraction_synthetic = n_cells / (n_total + 1e-8)
        fraction_real = 1.0 - fraction_synthetic
        normalized_scores = raw_scores / (fraction_synthetic + fraction_real + 1e-8)

        # Clamp scores to [0, 1]
        doublet_scores = jnp.clip(normalized_scores, 0.0, 1.0)

        # Step 7: Soft threshold for predicted doublets
        threshold = self.config.expected_doublet_rate * 2.0
        predicted_doublets = jax.nn.sigmoid(
            self.config.threshold_temperature * (doublet_scores - threshold)
        )

        transformed_data = {
            **data,
            "doublet_scores": doublet_scores,
            "predicted_doublets": predicted_doublets,
        }

        return transformed_data, state, metadata
